# Configures the system log output.
log:
  level: debug # Only supports debug, info, warn, error, panic, or fatal. Default 'info'.
  console: true # whether print log to console
  file:
    rootPath: "logs/backup.log"

http:
  simpleResponse: true


#milvus:
#  address: https://in01-b7d513aa1453f22.aws-us-west-2.vectordb-uat3.zillizcloud.com
#  port: 19542
#  authorizationEnabled: true
#  # tls mode values [0, 1, 2]
#  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
#  tlsMode: 0
#  user: "root"
#  password: "xxxxxx"

milvus:
  address: https://in01-b96c7b1ed4238f3.aws-us-west-2.vectordb-uat3.zillizcloud.com
  port: 19530
  authorizationEnabled: true
  # tls mode values [0, 1, 2]
  # 0 is close, 1 is one-way authentication, 2 is two-way authentication.
  tlsMode: 0
  user: "root"
  password: "xxxxxx"

# Related configuration of minio, which is responsible for data persistence for Milvus.
minio:
  cloudProvider: "aws" # remote cloud storage provider: s3, gcp, aliyun, azure

  address: s3.us-west-2.amazonaws.com # Address of MinIO/S3
  port: 443   # Port of MinIO/S3
  accessKeyID: AKIAUO3PULYA55SCQOKJ  # accessKeyID of MinIO/S3
  secretAccessKey: xxxxx # MinIO/S3 encryption string
  useSSL: true # Access to MinIO/S3 with SSL
  useIAM: false
  iamEndpoint: ""

  bucketName: "zilliz-aws-us-west-2-wdxlw6gkyo" # Milvus Bucket name in MinIO/S3, make it the same as your milvus instance
  rootPath: "b7d513aa1453f22" # Milvus storage root path in MinIO/S3, make it the same as your milvus instance

  backupAccessKeyID: AKIAUO3PULYA55SCQOKJ  # accessKeyID of MinIO/S3
  backupSecretAccessKey: xxxx # MinIO/S3 encryption string

  backupBucketName: "backup-test-tmp" # Bucket name to store backup data. Backup data will store to backupBucketName/backupRootPath
  backupRootPath: "b7d513aa1453f22" # Rootpath to store backup data. Backup data will store to backupBucketName/backupRootPath

  # refactor split backup and restore configs into different group
  backupCloudProvider: "aws" # remote cloud storage provider: s3, gcp, aliyun, azure
  backupAddress: s3.us-west-2.amazonaws.com # Address of MinIO/S3
  backupPort: 443
  backupUseSSL: true

backup:
  maxSegmentGroupSize: 2G
  parallelism: 2 # collection level parallelism to backup
  copydata:
    # thread pool to copy data for each collection backup, default 100. 
    # which means if you set backup.parallelism = 2 backup.copydata.parallelism = 100, there will be 200 copy executing at the same time.
    # reduce it if blocks your storage's network bandwidth
    parallelism: 128
  keepTempFiles: false

restore:
  # Collection level parallelism to restore
  # Only change it > 1 when you have more than one datanode.
  # Because the max parallelism of Milvus bulkinsert is equal to datanodes' number.
  parallelism: 2